import Footer from "@/components/Footer";
import "./globals.css";

export const metadata = {
  title: "My portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" mx-auto flex flex-col min-h-full text-gray-800">
        {children}
        <Footer />
      </body>
    </html>
  );  
}
