import { Roboto_Slab } from 'next/font/google';
 
export const inter = Roboto_Slab({ subsets: ['latin'] });
import Footer from "@/components/Footer";
import "./globals.css";

export const metadata = {
  title: "My portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.className} antialiased`}>
      <body className=" mx-auto flex flex-col min-h-full text-gray-800">
        {children}
        <Footer />
      </body>
    </html>
  );  
}
